Algoritmo "EX-07"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/08/2020
Var
// Seção de Declarações das variáveis 
 Temperatura:inteiro
 

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreval("Escreva a temeratura que está fazendo na sua cidade")
 leia(temperatura)
 se(temperatura >= 25)entao
 escreva("Tá pegando fogo bichoO!!")
 senao
 escreva("Está deboa!!")
 fimse

Fimalgoritmo