Algoritmo "EX-02"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/08/2020
Var
// Seção de Declarações das variáveis 
x,y:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
  escreval("digite o valor de x")
  leia(x)
  escreval("digite o valor de y")
  leia(y)
  escreval(x>y)
  escreva("x é maior que y")

Fimalgoritmo