Algoritmo "EX-12"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/08/2020
Var
// Seção de Declarações das variáveis 
Idade,Dias:inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreval("escreva sua idade ")
 leia(Idade)
 Dias<-Idade*365
 escreval("quantidade de dias que vc já viveu ",=Dias)

Fimalgoritmo