Algoritmo "EX-10"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/08/2020
Var
// Seção de Declarações das variáveis 
Numero_A:inteiro
Numero_B:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreval("Numero_A")
 leia(Numero_A)

 escreval("Numero_B")
 leia(Numero_B)

 se(Numero_A<>Numero_B)entao
 escreval(Numero_B)
 escreval(Numero_A)
 fimse
Fimalgoritmo