Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/08/2020
Var
// Seção de Declarações das variáveis 
Matriculas: vetor[0..100]de real
Alunos: real
i:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 para i de 0 ate 100 faca
 escreval("Digite o numero dessa matricula: ",Matriculas[Alunos])
 fimpara

Fimalgoritmo