Algoritmo "Vetor_3-13.08"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/08/2020
Var
// Seção de Declarações das variáveis 
VT1 : vetor [0..50]de real
VT2: vetor [0..50] de real
i:inteiro
 soma:real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para i de 0 ate 49 faca
escreval("Digite um numero: ",i+1)

leia(VT1[i])

fimpara

VT1[i]<-(soma*3)



Fimalgoritmo