Algoritmo "Vetor_2-13.08"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/08/2020
Var
Numeros: vetor[0..200]de real
i:inteiro
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  para i de 1 ate 200 faca
  escreval("Digite um numero: ",i+1)
  leia(Numeros[i])
  fimpara

Fimalgoritmo